### PR TITLE
Add JSON editor code lens

### LINKED ISSUE #13: Add "Ask FlowFuse" to JSON editors

### PR DESCRIPTION
**Pull request by Steve-Mcl**
closes #13

## Description

NOTE: Release not to be tagged until after https://github.com/FlowFuse/flowfuse/issues/4126 is merged

* Adds the code lens to JSON editors

## Related Issue(s)

#13 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

**Comment by joepavitt** [comment]
What would the "assistant scope" be here? It's not clear to me where this is set?

**Comment by Steve-Mcl** [comment]
> What would the "assistant scope" be here? It's not clear to me where this is set?

The scope is "All JSON Editors" including but not limited to
* template node
* inject node
* change node
* any node that fires up the monaco editor in JSON mode including contrib nodes via TypedInput.

Here is 2 quick demos

chrome_Hns4J0NG7P

The benefit is a seamless integration with all the nodes they use (core and contrib) in their FF Cloud instance.

**Comment by joepavitt** [comment]
Sorry, I should have been more specific, in the flow, we add the "assistant scope" from part of the body of the request. What is the differentiating key here to ensure we know it's come from the JSON editor?

**Comment by Steve-Mcl** [comment]
> Sorry, I should have been more specific, in the flow, we add the "assistant scope" from part of the body of the request. What is the differentiating key here to ensure we know it's come from the JSON editor?

I guessed after posting - see previous reply.  Does that help?

**Review by joepavitt — APPROVED** [review]

**Pull request merged**
